### 2.2 배열과 벡터 공간

2.2.1 간단한 벡터의 정의

In [1]:
x = [-3, pi, 0, 1]

4-element Vector{Float64}:
 -3.0
  3.141592653589793
  0.0
  1.0

In [2]:
# 영벡터와 랜덤벡터
zeros(3)

3-element Vector{Float64}:
 0.0
 0.0
 0.0

In [3]:
rand(3)

3-element Vector{Float64}:
 0.9372009702869065
 0.0730983110475516
 0.2831417526758462

In [4]:
randn(3)

3-element Vector{Float64}:
  1.8319949478555773
 -1.8406025226237903
 -1.1734285829462183

In [5]:
# 반복벡터
ones(3)

3-element Vector{Float64}:
 1.0
 1.0
 1.0

In [6]:
fill(7, 3)

3-element Vector{Int64}:
 7
 7
 7

In [7]:
repeat([0,1], 2)

4-element Vector{Int64}:
 0
 1
 0
 1

2.2.2 레인지와 등차수열

In [8]:
b = 1:100

1:100

In [9]:
c = 2:2:100

2:2:100

In [10]:
c[23]

46

In [15]:
@show collect(c);

collect(c) = [2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]


In [16]:
sizeof(c)

24

In [17]:
sizeof(collect(c))

400

In [18]:
# 선형 레인지
LinRange(0, 1, 100)

100-element LinRange{Float64, Int64}:
 0.0, 0.010101, 0.020202, 0.030303, …, 0.969697, 0.979798, 0.989899, 1.0

2.2.3 벡터 공간

In [1]:
# 벡터의 연산
e = exp(1);

In [2]:
u = [4, π, 1, -2];

In [4]:
v = [0, -9, 0, e];

In [5]:
u + v

4-element Vector{Float64}:
  4.0
 -5.858407346410207
  1.0
  0.7182818284590451

In [6]:
u - v

4-element Vector{Float64}:
  4.0
 12.141592653589793
  1.0
 -4.718281828459045

In [7]:
e * u

4-element Vector{Float64}:
 10.87312731383618
  8.539734222673566
  2.718281828459045
 -5.43656365691809

In [8]:
u / π

4-element Vector{Float64}:
  1.2732395447351628
  1.0
  0.3183098861837907
 -0.6366197723675814

In [9]:
# 수학적 근거로써의 벡터 공간
u + π

LoadError: MethodError: no method matching +(::Vector{Float64}, ::Irrational{:π})
For element-wise addition, use broadcasting with dot syntax: array .+ scalar

Closest candidates are:
  +(::Any, ::Any, ::Any, ::Any...)
   @ Base operators.jl:587
  +(::Complex{Bool}, ::Real)
   @ Base complex.jl:320
  +(::Missing, ::Number)
   @ Base missing.jl:123
  ...


In [10]:
u .+ π

4-element Vector{Float64}:
 7.141592653589793
 6.283185307179586
 4.141592653589793
 1.1415926535897931